Add token validation

diff --git a/sintesis b/sintesis
--- a/sintesis
+++ b/sintesis
@@ -12,6 +12,7 @@ public_token()
 public_scan()
 {
 	TOKEN=$1
+	token_check $TOKEN
 	while true; do
 		echo -n "$TOKEN: "
 		user_name $TOKEN
@@ -22,21 +23,34 @@ public_scan()
 public_view()
 {
 	TOKEN=$1
+	token_check $TOKEN
 	echo -n "Name: "
 	user_name $TOKEN
 	echo -n "Wi-Fi account: "
 	user_wifi $TOKEN
 }
 
+token_check()
+{
+	TOKEN=$1
+	regex='^[0-9]+$'
+	if ! [[ $TOKEN =~ $regex ]]
+	then
+		echo "Error: Invalid token" >&2
+	exit 1
+	fi
+}
 user_logout()
 {
 	TOKEN=$1
+	token_check $TOKEN
 	curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=0000%7C0000" $URL/index.php?logout=1
 }
 
 user_name()
 {
 	TOKEN=$1
+	token_check $TOKEN
 	out=$(curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=10%7C1000" \
 	$URL/index.php | \
 	grep "<td align='center'><b>" | \
@@ -48,6 +62,7 @@ user_name()
 user_wifi()
 {
 	TOKEN=$1
+	token_check $TOKEN
 	curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=10%7C1000"  \
 	"$URL/index.php?MS=1000|210" | \
 	grep -E '<td class=a>.*Username|<td class=a>.*Password|<td class=a>.*MAC' | \
